server.port=8081

## Shows detailed authentication and filter decisions in the console
#logging.level.org.springframework.security=DEBUG
## Even more detail if DEBUG isn't enough
#logging.level.org.springframework.security.web=TRACE
